-- Replace tag vocabulary in `tags` (locations may still contain legacy comma-separated names until edited).
DELETE FROM tags;

INSERT INTO tags (name) VALUES
    ('AIDS'),
    ('HIV'),
    ('STIs'),
    ('Fetisch'),
    ('Cruising'),
    ('Pride-Parade'),
    ('Religion'),
    ('Inter*'),
    ('Jung'),
    ('Kultur'),
    ('Kino'),
    ('Kunst'),
    ('Ausstellung'),
    ('lgbtiqa*'),
    ('Männer'),
    ('Frauen'),
    ('nonbinary'),
    ('PrEP'),
    ('Sex'),
    ('Sexualität'),
    ('Sport'),
    ('Therapie'),
    ('trans'),
    ('Test'),
    ('Hotline'),
    ('Tanzen'),
    ('Workshop'),
    ('Coming Out'),
    ('Party'),
    ('Drag'),
    ('Show'),
    ('Vorträge');
