name: Setup GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      env_file:
        description: 'Path to .env file'
        required: true
        default: '.env'

jobs:
  setup-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Login to GitHub
        run: gh auth login --with-token < <(echo "${{ secrets.GITHUB_TOKEN }}")

      - name: Set Secrets from .env
        run: |
          while IFS='=' read -r key value; do
            # Skip empty lines and comments
            [[ -z "$key" || "$key" =~ ^# ]] && continue
            
            # Remove quotes from value
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")
            
            # Skip if key or value is empty
            [[ -z "$key" || -z "$value" ]] && continue
            
            echo "Setting secret: $key"
            echo "$value" | gh secret set "$key" --repo "${{ github.repository }}"
          done < "${{ github.event.inputs.env_file }}" 